// Skills Database - Curated from ClawHub and awesome-openclaw-skills
const skillsData = [
    // Featured/Popular Skills
    {
        id: "github",
        name: "GitHub",
        slug: "github",
        description: "Managed OAuth, handles repos, issues, PRs, commits. Essential for dev work. Your agent can create issues, review PRs, search code without touching the GitHub UI.",
        category: "Git & GitHub",
        author: "steipete",
        downloads: 8500,
        trustScore: 95,
        tags: ["development", "version-control", "automation"],
        featured: true,
        installCommand: "npx clawhub@latest install github"
    },
    {
        id: "agentmail",
        name: "AgentMail",
        slug: "agentmail",
        description: "Email infrastructure for agents. Create inboxes programmatically, handle verifications, manage multiple agent identities. Let your agents sign up for services and handle email tasks.",
        category: "Communication",
        author: "official",
        downloads: 6200,
        trustScore: 92,
        tags: ["email", "automation", "identity"],
        featured: true,
        installCommand: "npx clawhub@latest install agentmail"
    },
    {
        id: "linear",
        name: "Linear",
        slug: "linear",
        description: "GraphQL-based project management. Manages issues, projects, teams, cycles. Create and update Linear issues directly from OpenClaw. Way faster than switching between apps.",
        category: "Productivity & Tasks",
        author: "official",
        downloads: 5800,
        trustScore: 90,
        tags: ["productivity", "project-management", "collaboration"],
        featured: true,
        installCommand: "npx clawhub@latest install linear"
    },
    {
        id: "playwright-mcp",
        name: "Playwright MCP",
        slug: "playwright-mcp",
        description: "Full browser automation. Navigate websites, click elements, fill forms, take screenshots. Complete browser automation workflows for complex tasks.",
        category: "Browser & Automation",
        author: "official",
        downloads: 7200,
        trustScore: 88,
        tags: ["browser", "automation", "scraping"],
        featured: true,
        installCommand: "npx clawhub@latest install playwright-mcp"
    },
    {
        id: "obsidian-direct",
        name: "Obsidian Direct",
        slug: "obsidian-direct",
        description: "Knowledge base integration. Fuzzy search across notes, auto-folder detection, manage tags and wikilinks. Your agent can query your Obsidian vault as a knowledge base.",
        category: "Notes & PKM",
        author: "official",
        downloads: 4900,
        trustScore: 87,
        tags: ["notes", "knowledge-management", "search"],
        featured: true,
        installCommand: "npx clawhub@latest install obsidian-direct"
    },
    {
        id: "automation-workflows",
        name: "Automation Workflows",
        slug: "automation-workflows",
        description: "Workflow builder that helps design automation workflows across tools. Identifies repetitive tasks and sets up triggers/actions. Teaches your agent to build workflows.",
        category: "Self-Hosted & Automation",
        author: "official",
        downloads: 5100,
        trustScore: 86,
        tags: ["automation", "workflows", "productivity"],
        featured: true,
        installCommand: "npx clawhub@latest install automation-workflows"
    },
    {
        id: "monday",
        name: "Monday",
        slug: "monday",
        description: "If your team uses Monday for project tracking, this is clutch. Agent can create items, update boards, manage tasks. 2.5k+ downloads.",
        category: "Productivity & Tasks",
        author: "official",
        downloads: 2500,
        trustScore: 85,
        tags: ["project-management", "tasks", "collaboration"],
        featured: false,
        installCommand: "npx clawhub@latest install monday"
    },
    {
        id: "nextjs16-docs",
        name: "NextJS 16+ Documentation",
        slug: "lb-nextjs16-skill",
        description: "Entire NextJS 16 documentation in markdown. Useful when building or debugging NextJS projects. Always up-to-date reference.",
        category: "Web & Frontend Development",
        author: "lb",
        downloads: 3200,
        trustScore: 84,
        tags: ["nextjs", "documentation", "development"],
        featured: false,
        installCommand: "npx clawhub@latest install lb-nextjs16-skill"
    },
    {
        id: "playwright-scraper",
        name: "Playwright Scraper",
        slug: "playwright-scraper-skill",
        description: "Web scraping with anti-bot protection. Successfully tested on complex sites. When you need actual browser automation that bypasses bot detection.",
        category: "Browser & Automation",
        author: "official",
        downloads: 4100,
        trustScore: 83,
        tags: ["scraping", "automation", "browser"],
        featured: false,
        installCommand: "npx clawhub@latest install playwright-scraper-skill"
    },
    {
        id: "claude-code",
        name: "Claude Code",
        slug: "coding-agent",
        description: "Run Codex CLI, Claude Code, OpenCode, or Pi Coding Agent for complex development tasks. Multi-agent coding orchestration.",
        category: "Coding Agents & IDEs",
        author: "steipete",
        downloads: 6800,
        trustScore: 91,
        tags: ["coding", "ai-agents", "development"],
        featured: true,
        installCommand: "npx clawhub@latest install coding-agent"
    },
    {
        id: "moltbook",
        name: "Moltbook",
        slug: "moltbook",
        description: "The social network for AI agents. Connect, share, and collaborate with other AI agents in the ecosystem.",
        category: "Moltbook",
        author: "mattprd",
        downloads: 3800,
        trustScore: 79,
        tags: ["social", "networking", "agents"],
        featured: false,
        installCommand: "npx clawhub@latest install moltbook"
    },
    {
        id: "docker-essentials",
        name: "Docker Essentials",
        slug: "docker-essentials",
        description: "Essential Docker commands and workflows for container management. Build, run, and manage containers effortlessly.",
        category: "DevOps & Cloud",
        author: "arnarsson",
        downloads: 4600,
        trustScore: 88,
        tags: ["docker", "containers", "devops"],
        featured: false,
        installCommand: "npx clawhub@latest install docker-essentials"
    },
    {
        id: "web-search",
        name: "Web Search",
        slug: "exa-web-search-free",
        description: "Free AI search via Exa. Search the web with advanced AI-powered queries and get relevant results.",
        category: "Search & Research",
        author: "whiteknight07",
        downloads: 5300,
        trustScore: 82,
        tags: ["search", "research", "ai"],
        featured: false,
        installCommand: "npx clawhub@latest install exa-web-search-free"
    },
    {
        id: "git-workflows",
        name: "Git Workflows",
        slug: "git-workflows",
        description: "Advanced git operations beyond add/commit/push. Master branching, rebasing, cherry-picking, and more.",
        category: "Git & GitHub",
        author: "gitgoodordietrying",
        downloads: 3900,
        trustScore: 86,
        tags: ["git", "version-control", "workflows"],
        featured: false,
        installCommand: "npx clawhub@latest install git-workflows"
    },
    {
        id: "telegram",
        name: "Telegram",
        slug: "telegram",
        description: "Full Telegram integration. Send messages, manage groups, create bots, handle media. Complete control over Telegram.",
        category: "Communication",
        author: "official",
        downloads: 6100,
        trustScore: 89,
        tags: ["telegram", "messaging", "bots"],
        featured: false,
        installCommand: "npx clawhub@latest install telegram"
    },
    {
        id: "slack",
        name: "Slack",
        slug: "slack",
        description: "Slack workspace integration. Send messages, manage channels, post updates, handle notifications.",
        category: "Communication",
        author: "official",
        downloads: 4700,
        trustScore: 87,
        tags: ["slack", "messaging", "collaboration"],
        featured: false,
        installCommand: "npx clawhub@latest install slack"
    },
    {
        id: "notion",
        name: "Notion",
        slug: "notion",
        description: "Notion workspace integration. Create pages, update databases, manage tasks, organize knowledge.",
        category: "Notes & PKM",
        author: "official",
        downloads: 5500,
        trustScore: 88,
        tags: ["notion", "productivity", "knowledge-management"],
        featured: false,
        installCommand: "npx clawhub@latest install notion"
    },
    {
        id: "google-calendar",
        name: "Google Calendar",
        slug: "google-calendar",
        description: "Manage Google Calendar events. Create, update, delete events. Schedule meetings automatically.",
        category: "Calendar & Scheduling",
        author: "official",
        downloads: 4200,
        trustScore: 85,
        tags: ["calendar", "scheduling", "google"],
        featured: false,
        installCommand: "npx clawhub@latest install google-calendar"
    },
    {
        id: "twitter-x",
        name: "Twitter/X",
        slug: "twitter",
        description: "Twitter/X integration. Post tweets, reply, like, retweet. Full social media automation.",
        category: "Social Media",
        author: "official",
        downloads: 7800,
        trustScore: 84,
        tags: ["twitter", "social-media", "automation"],
        featured: false,
        installCommand: "npx clawhub@latest install twitter"
    },
    {
        id: "discord",
        name: "Discord",
        slug: "discord",
        description: "Discord bot integration. Send messages, manage servers, handle events, moderate communities.",
        category: "Communication",
        author: "official",
        downloads: 5900,
        trustScore: 86,
        tags: ["discord", "bots", "community"],
        featured: false,
        installCommand: "npx clawhub@latest install discord"
    },
    // Add more skills from different categories
    {
        id: "home-assistant",
        name: "Home Assistant",
        slug: "moltbot-ha",
        description: "Control Home Assistant smart home devices, lights, scenes, and automations directly from your agent.",
        category: "Smart Home & IoT",
        author: "iamvaleriofantozzi",
        downloads: 2800,
        trustScore: 81,
        tags: ["smart-home", "iot", "automation"],
        featured: false,
        installCommand: "npx clawhub@latest install moltbot-ha"
    },
    {
        id: "elevenlabs-tts",
        name: "ElevenLabs TTS",
        slug: "elevenlabs",
        description: "Text-to-speech with ElevenLabs. Generate natural-sounding voice audio from text with multiple voice options.",
        category: "Speech & Transcription",
        author: "official",
        downloads: 4400,
        trustScore: 87,
        tags: ["tts", "voice", "audio"],
        featured: false,
        installCommand: "npx clawhub@latest install elevenlabs"
    },
    {
        id: "stripe",
        name: "Stripe",
        slug: "stripe",
        description: "Stripe payment integration. Handle payments, subscriptions, invoices, and customer management.",
        category: "Finance",
        author: "official",
        downloads: 3600,
        trustScore: 90,
        tags: ["payments", "finance", "stripe"],
        featured: false,
        installCommand: "npx clawhub@latest install stripe"
    },
    {
        id: "gmail",
        name: "Gmail",
        slug: "gmail",
        description: "Gmail integration. Read, send, organize emails. Manage labels, filters, and automate email workflows.",
        category: "Communication",
        author: "official",
        downloads: 6700,
        trustScore: 89,
        tags: ["email", "gmail", "automation"],
        featured: false,
        installCommand: "npx clawhub@latest install gmail"
    },
    {
        id: "trello",
        name: "Trello",
        slug: "trello",
        description: "Trello board integration. Manage cards, lists, boards. Perfect for kanban-style project management.",
        category: "Productivity & Tasks",
        author: "official",
        downloads: 3100,
        trustScore: 83,
        tags: ["trello", "project-management", "kanban"],
        featured: false,
        installCommand: "npx clawhub@latest install trello"
    }
];

// Categories with icons and counts
const categories = [
    { id: "coding-agents", name: "Coding Agents & IDEs", icon: "💻", count: 133, slug: "coding-agents" },
    { id: "git-github", name: "Git & GitHub", icon: "🔀", count: 66, slug: "git-github" },
    { id: "web-frontend", name: "Web & Frontend Development", icon: "🎨", count: 202, slug: "web-frontend" },
    { id: "devops-cloud", name: "DevOps & Cloud", icon: "☁️", count: 212, slug: "devops-cloud" },
    { id: "browser-automation", name: "Browser & Automation", icon: "🤖", count: 139, slug: "browser-automation" },
    { id: "productivity", name: "Productivity & Tasks", icon: "✅", count: 135, slug: "productivity" },
    { id: "communication", name: "Communication", icon: "💬", count: 132, slug: "communication" },
    { id: "marketing-sales", name: "Marketing & Sales", icon: "📈", count: 143, slug: "marketing-sales" },
    { id: "ai-llms", name: "AI & LLMs", icon: "🧠", count: 287, slug: "ai-llms" },
    { id: "notes-pkm", name: "Notes & PKM", icon: "📝", count: 100, slug: "notes-pkm" },
    { id: "social-media", name: "Social Media", icon: "📱", count: 95, slug: "social-media" },
    { id: "search-research", name: "Search & Research", icon: "🔍", count: 253, slug: "search-research" },
    { id: "smart-home", name: "Smart Home & IoT", icon: "🏠", count: 56, slug: "smart-home" },
    { id: "speech-transcription", name: "Speech & Transcription", icon: "🎤", count: 65, slug: "speech-transcription" },
    { id: "security", name: "Security & Passwords", icon: "🔒", count: 63, slug: "security" },
    { id: "finance", name: "Finance", icon: "💰", count: 22, slug: "finance" },
    { id: "calendar", name: "Calendar & Scheduling", icon: "📅", count: 50, slug: "calendar" },
    { id: "pdf-documents", name: "PDF & Documents", icon: "📄", count: 67, slug: "pdf-documents" },
    { id: "media-streaming", name: "Media & Streaming", icon: "🎬", count: 80, slug: "media-streaming" },
    { id: "image-video", name: "Image & Video Generation", icon: "🖼️", count: 60, slug: "image-video" },
    { id: "moltbook", name: "Moltbook", icon: "🦞", count: 51, slug: "moltbook" },
    { id: "gaming", name: "Gaming", icon: "🎮", count: 61, slug: "gaming" },
    { id: "health-fitness", name: "Health & Fitness", icon: "💪", count: 55, slug: "health-fitness" },
    { id: "transportation", name: "Transportation", icon: "🚗", count: 73, slug: "transportation" }
];
